# stream-quatation/Cargo.toml
[workspace]
members = [
    "quote_app",
    "quote_lib",
]

# Общие настройки для всех членов workspace
[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Eugen Batts"]
license = "MIT"

