[package]
name = "quote-server-old"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam-channel="0.5"
quote-lib ={path = "../quote_lib"}
rand = "0.10.0-rc.5"
thiserror = "2.0"
clap = "4.5"
log = "0.4"
env_logger = "0.11"
chrono = "0.4"
