[package]
name = "quote-client"
version = "0.1.0"
edition = "2024"

[dependencies]
quote-lib ={path = "../quote_lib"}
thiserror = "2.0"
socket2 = "0.6"
clap = { version ="4.5" , features = ["derive"] }
log = "0.4"
env_logger = "0.11"
chrono = "0.4"